import { KSection } from "./Section";

const POINTS = [
  { icon: "🎨", title: "Hand-Crafted by Google", desc: "Every sticker is individually illustrated by Google's Noto Emoji design team — not generated by AI. Each passes through human review before shipping." },
  { icon: "🔍", title: "Lookup, Not Generation", desc: "When you tap two emojis, Gboard checks whether a pre-drawn sticker exists for that pair and retrieves it from Google's servers. No on-the-fly generation." },
  { icon: "🖼️", title: "Images, Not Characters", desc: "Emoji Kitchen outputs are PNG sticker files, not Unicode text. They travel through messaging apps as pictures — which is why they work in WhatsApp but not in Twitter/X comment boxes." },
  { icon: "📊", title: "100,000+ Combinations", desc: "Google surpassed 100,000 unique hand-crafted combinations around World Emoji Day 2025 — and the library keeps growing with each Gboard update." },
];

export default function WhatIsEmojiKitchen() {
  return (
    <KSection kicker="Overview" title="What Is Emoji Kitchen?">
      <div className="fg-prose max-w-3xl mb-8">
        <p>Emoji Kitchen is a feature built into Google&apos;s Gboard keyboard that combines two standard emojis into a single, hand-crafted sticker image. On Android it works natively inside Gboard; iPhone users access it through the Google Search web interface at google.com.</p>
        <p>The output is not a modified emoji character. It is a standalone sticker image — a rasterized illustration that travels through messaging apps as a picture, not as text. That distinction shapes where it works, how it fails, and why it produces results no combination of standard Unicode emojis could replicate.</p>
      </div>

      <div className="fg-list mb-8">
        {POINTS.map((p) => (
          <div key={p.title} className="fg-entry fg-entry--ledger">
            <span className="fg-entry__glyph" style={{ fontSize: "1.5rem" }}>{p.icon}</span>
            <div className="fg-entry__main">
              <span className="fg-entry__name">{p.title}</span>
              <p className="fg-entry__text">{p.desc}</p>
            </div>
          </div>
        ))}
      </div>

      <div className="fg-pull fg-pull--sm">
        <span className="fg-kicker">Key Distinction</span>
        <p>Standard emojis are Unicode characters that each OS renders in its own font. Emoji Kitchen outputs have no Unicode equivalent — they are rasterized PNGs that exist independently of any text layer, which is why they work in apps that accept image attachments but fail in plain text fields.</p>
      </div>
    </KSection>
  );
}
