import { AnimatedSection } from "@/components/MotionWrappers";

const POINTS = [
  { icon: "🎨", title: "Hand-Crafted by Google", desc: "Every sticker is individually illustrated by Google's Noto Emoji design team — not generated by AI. Each passes through human review before shipping." },
  { icon: "🔍", title: "Lookup, Not Generation", desc: "When you tap two emojis, Gboard checks whether a pre-drawn sticker exists for that pair and retrieves it from Google's servers. No on-the-fly generation." },
  { icon: "🖼️", title: "Images, Not Characters", desc: "Emoji Kitchen outputs are PNG sticker files, not Unicode text. They travel through messaging apps as pictures — which is why they work in WhatsApp but not in Twitter/X comment boxes." },
  { icon: "📊", title: "100,000+ Combinations", desc: "Google celebrated surpassing 100,000 unique hand-crafted combinations around World Emoji Day 2025 — and the library continues growing with each Gboard update." },
];

export default function WhatIsEmojiKitchen() {
  return (
    <section className="py-14 rule-top">
      <div className="max-w-5xl mx-auto px-4">
        <AnimatedSection>
          <p className="eyebrow mb-3 flex items-center gap-2"><span className="inline-block w-6 h-px bg-primary" aria-hidden="true" />Overview</p>
          <h2 className="font-display text-3xl sm:text-4xl text-primary-dark dark:text-white leading-[1.1] mb-4">
            What Is Emoji Kitchen?
          </h2>
          <p className="text-neutral-600 dark:text-slate-300 leading-relaxed mb-3 max-w-3xl">
            Emoji Kitchen is a feature built into Google&apos;s Gboard keyboard that combines two standard emojis into a single, hand-crafted sticker image. On Android, it works natively inside Gboard; iPhone users can access it through the Google Search web interface at google.com.
          </p>
          <p className="text-neutral-600 dark:text-slate-300 leading-relaxed mb-8 max-w-3xl">
            The output is not a modified emoji character. It is a standalone sticker image — a rasterized illustration that travels through messaging apps as a picture, not as text. That distinction shapes where it works, how it fails, and why it produces results that no combination of standard Unicode emojis could replicate.
          </p>
        </AnimatedSection>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-8">
          {POINTS.map((point) => (
            <AnimatedSection key={point.title}>
              <div className="bg-neutral-50 dark:bg-slate-800 rounded-2xl p-5 border border-neutral-200/80 dark:border-slate-700 shadow-sm card-lift hover:shadow-md hover:border-primary/40">
                <div className="flex items-center gap-3 mb-2">
                  <span className="text-2xl">{point.icon}</span>
                  <h3 className="font-bold text-primary-dark dark:text-white">{point.title}</h3>
                </div>
                <p className="text-sm text-neutral-600 dark:text-slate-400 leading-relaxed">{point.desc}</p>
              </div>
            </AnimatedSection>
          ))}
        </div>

        <AnimatedSection>
          <div className="bg-indigo-50 dark:bg-indigo-950/30 border-l-4 border-primary rounded-r-xl p-5">
            <h3 className="font-bold text-primary-dark dark:text-white mb-1">Emoji Kitchen vs. Regular Emojis — What Is the Difference?</h3>
            <p className="text-sm text-neutral-600 dark:text-slate-300 leading-relaxed">
              Standard emojis are Unicode characters — text code points that every OS renders through its own emoji font. The 😂 you type on Android looks different from the 😂 on iOS because each platform draws its own version. Emoji Kitchen outputs have no Unicode equivalent. They are rasterized image files — PNGs that exist independently of any text layer. This is why they work in messaging apps that accept image attachments but fail in plain text fields.
            </p>
          </div>
        </AnimatedSection>
      </div>
    </section>
  );
}
